name: Build and Deploy

on:
  push:
    branches: [yeshu]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist

  # sync-to-gitee:
  #   runs-on: ubuntu-latest
  #   if: github.repository == 'xdlrt/md'
  #   needs: build-and-deploy
  #   steps:
  #     - name: Sync to Gitee
  #       uses: wearerequired/git-mirror-action@v1
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
  #       with:
  #         source-repo: git@github.com:doocs/md.git
  #         destination-repo: git@gitee.com:Doocs/md.git
